version: '3.8'
services:
  api-gateway:
    build: ./api_gateway
    ports:
      - "5000:5000"
  user-service:
    build: ./user_service
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data
  nlp-service:
    build: ./nlp_service
    ports:
      - "5002:5002"
  dialogue-service:
    build: ./dialogue_service
    ports:
      - "5003:5003"
    volumes:
      - ./data:/app/data
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"